from main import add_note, change_note, change_note_stat, show_notes, show_tags, del_note, search_note, NotePad

notebook = NotePad()
(add_note(notebook, "test"))
(add_note(notebook, "test 132 test"))
(add_note(notebook, "test1"))
(add_note(notebook, "#test wee we"))
(add_note(notebook, "#test"))
# print(change_note(notebook, "#test"))
# print(change_note_stat(notebook, "test"))
# print(del_note(notebook, "test"))
print(search_note(notebook, "te"))
print(search_note(notebook, "#te"))
print(show_notes(notebook))
print(show_tags(notebook))
